### ISSUE TITLE
Methodology

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/covid-19-cases-vs-tests-analysis#34]
Hello,

The nature of the data you are using is temporal, which means there is autocorrelation within each country's response rate data. I think you should consider that in the analysis or at least consider that as a limitation to your analysis.

If you have time, I suggest you skim throught the following stack exchange discussion:

https://stats.stackexchange.com/questions/7319/two-sample-t-test-for-data-maybe-time-series-with-autocorrelation

**Comment by tanmaysharma19** [comment]
Acknowledged. The same has been addressed in the summary report #48 .
