### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/covid-19-cases-vs-tests-analysis#35]
You don't need to upload the data folder to github. The best practice is to include it in your local repos, but add it to the `.gitignore` file.

**Comment by fatse** [comment]
@hsmohammed just to make sure I am understanding this correctly, you mean we don't need to upload our `.csv` files in the data folder?

**Comment by tanmaysharma19** [comment]
@hsmohammed , to add to Fatime's question we pushed our data folder and the `.csv` files as per the model project shared by Tiffany in class(https://github.com/ttimbers/equine_numbers_value_canada_parameters). Would appreciate you helping us better understand your feedback. Thank you.

**Comment by tanmaysharma19** [comment]
Acknowledged Hossam's response as received on Slack, "Regarding the csv file, yes I advice you not to upload the csv file on Canvas as you don't need to. A user would clone the repo and use your script to download data. I didn't deduct any marks for that."
