### ISSUE TITLE
Team Contract

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/covid-19-cases-vs-tests-analysis#5]
Group24 Team Contract for collaboration throughout DSCI-522.
[Group24-Team-Contract-DSCI-522.pdf](https://github.com/UBC-MDS/dsci-522-group-24/files/5563805/Group24-Team-Contract-DSCI-522.pdf)

**Comment by fatse** [comment]
LGTM.

**Comment by tanmaysharma19** [comment]
Team Contract was reviewed and adopted by the group.
