### ISSUE TITLE
TA Feedback (milestone 2): Plots & tables

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/covid-19-cases-vs-tests-analysis#64]
- Figure 2 is not really needed. We used these plots in Inference I primarily for teaching, they are not meant for communicating to an audience.
- You can improve figure 1 by aligning the scales of the x-axis to make it easier to compare the two distributions visually.

**Comment by tanmaysharma19** [comment]
@jbourak Thank you for your feedback. Acknowledged as per our discussion on Slack, will incorporate the suggested changes.

**Comment by nichowu** [comment]
The second point has been addressed in PR #68

**Comment by tanmaysharma19** [comment]
First point of Jordan's feedback was addressed in PR #73.
