### ISSUE TITLE
Inferential question about Covid-19 dataset

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/covid-19-cases-vs-tests-analysis#7]
Hi folks,

Let's add here our ideas for the inferential question that we'll potentially answer about the Covid-19 data set (link attached below).

Data set link: https://github.com/owid/covid-19-data/tree/master/public/data

**Comment by nichowu** [comment]
Are the increasing rates of confirmed cases the same between 
two countries (developed v. less developed)or not? 
(time period to compare: the first three months after the virus broke out)

Implications: 
If they are the same, it would indicate that the transmission may be only dependent
on the virus own properties.
If they are not the same, it would indicate that the transmission may be dependent on other 
factors such as population density, stringency level or age structure.

EDA table: rolling average of increasing rate?
EDA plot: points+line plot of new cases over time to look at the two countries' slop(increasing rate).

**Comment by nichowu** [comment]
New Tests/New Cases

Is the **_median_** ratio (# of new tests/# of new cases) on average, in developed country higher than less developed country
or not?

Implications:
If it is higher, it would indicate that developed country is more equipped to provide sufficient 
testing than less developed country. 

If it is lower or equal, it would indicate that developed country is not providing as many 
testing as less developed country. Subsequently we might want to look at potential reasons of that. 
Maybe developed country is more concerned about its economy as it doesn't want to raise panic among 
citizens by providing enough testing. 

EDA table: mean, variance, median, quantiles of new tests/new cases
EDA plot: bar plots of new tests v. population, new cases v. population?

**Comment by fatse** [comment]
An interesting question that could lead to an interesting inferential outcome would be:

> Is the number of Covid-19 active cases in Canada greater when the weather is warm, i.e. weather >= 20 &deg;C, compared to the number of Covid-19 active cases when the weather is not warm (weather < 20 &deg;C)?

I am aware that we cannot answer this inferential question with the data set that we already chose. I found a data set that provides the temperature along with the Covid-19 active/confirmed/recovered cases for each country. Alas, the data set is in Kaggle and we aren't encouraged to use data sets that have an extra layer of security when we try to download them.

Anyway, here's the data set that I'm talking about: https://www.kaggle.com/corochann/covid-19-effect-of-temperature-humidity

**Comment by tanmaysharma19** [comment]
Building up on the comparison theme, here are two inferential questions which I think might be interesting to explore :

- Comparing the proportion of confirmed cases / total tests between Canada and USA.
- Comparing the case fatality rate (proportion of confirmed deaths / confirmed cases) between Canada and USA.

**Comment by fatse** [comment]
We can tweak the question that I posted above a little and be able to answer it with the data set that we chose.
The question would be:

> Is the number of Covid-19 active cases in Canada greater when the weather is warm (during the summer), compared to the number of Covid-19 active cases when the weather is not warm (during the fall)?

To answer this question we would need to filter on `date` column in the data set that we already chose, with the assumption that the warm weather would be the dates from **20-06-2020** to **21-09-2020** (summer season) and the cold weather would the dates from **22-09-2020** to the most recent date that we have in the data set which is **18-11-2020** (fall season).

**Comment by nphaterp** [comment]
I had the idea of just looking at Canada and comparing the mortality/#cases from the first 4 months vs the most recent 4 months. Hopefully this would indicate whether there is a significant   a difference in the disease management within Canada since the start of the pandemic

**Comment by nichowu** [comment]
> We can tweak the question that I posted above a little and be able to answer it with the data set that we chose.
> The question would be:
> 
> > Is the number of Covid-19 active cases in Canada greater when the weather is warm (during the summer), compared to the number of Covid-19 active cases when the weather is not warm (during the fall)?
> 
> To answer this question we would need to filter on `date` column in the data set that we already chose, with the assumption that the warm weather would be the dates from **20-06-2020** to **21-09-2020** (summer season) and the cold weather would the dates from **22-09-2020** to the most recent date that we have in the data set which is **18-11-2020** (fall season).

Just a couple questions:
1. Do we have the active case amount in the dataset? I can't seem to find it. 
2. I feel like if we want to compare the impact that temperature change has on the number of active cases, then it would be best to compare the warmest dates with the coldest ones to see the full impact. I don't feel like we have reached the coldest weather  in Canada yet.
3. Overall I don't feel like it is a good idea to compare one test statistic in one country over two different time group. My reason is that things change over time so there will be a lot of factors we have to assume constant in our analysis. I'm not sure about this..

**Comment by nichowu** [comment]
> I had the idea of just looking at Canada and comparing the mortality/#cases from the first 4 months vs the most recent 4 months. Hopefully this would indicate whether there is a significant a difference in the disease management within Canada since the start of the pandemic

My thoughts on this:
I feel like one would argue that the mortality rate for the recent four month might have been affected by the first four months because there are so much other factors at play (e.g. government response). So if one group might have affected the other group, would it make the inferential question less valid? 

I don't feel like it is a good idea to compare one test statistic in one country over two different time groups. Jordan the TA also mentioned something about being careful on wording to avoid causality. Thoughts?

**Comment by nichowu** [comment]
> Building up on the comparison theme, here are two inferential questions which I think might be interesting to explore :
> 
> * Comparing the proportion of confirmed cases / total tests between Canada and USA.
> * Comparing the case fatality rate (proportion of confirmed deaths / confirmed cases) between Canada and USA.

The proportion of confirmed cases / total tests between CA and USA seems easy to understand so it has my vote. 
The fatality rate seems less meaningful to me because a lot of complications could be the cause of death. We might face challenge in wording the question? I dunno...

**Comment by fatse** [comment]
@nichowu yeah, I agree it's not perfect but it's an interesting question to ask nonetheless as part of the brainstorming. 

My initial ideas that I suggested yesterday in the meeting and that are captured in your two suggestions above are cleaner.
