### ISSUE TITLE
Group 24 - Peer Review

### ISSUE THREAD

**Issue by camharris22** [UBC-MDS/covid-19-cases-vs-tests-analysis#72]
Hello Group 24!

**Documentation:** 
- All docs were informative, succinct and well written. I really liked the formatting style of the report, it was very clean and professional. 
- Well organized Github repo, easy to navigate

**Code:**
- Everything ran smoothly for me once dependencies were installed
- Well written scripts and make file

**Analysis and reasoning:**
- Very controversial topic but good job stating your assumptions clearly. From what I retained in DSCI 552 the analysis makes sense to me 😃 
- It took me a bit of time when reading the report to think about what the "Response Ratio" was telling me (more discussion below) 

**Communication:**
- Purpose of analysis, methods used and results were well communicated

**Suggestions:**
- As far as the purpose of the course goals and milestone objectives go, I don't have anything that I would suggest changing. Your team knocked it out of the park, great job!

- I have some thoughts on the overall metric (response ratio) that may be more for discussion. So feel free to ignore this part 😅 

It's somewhat of a hot topic when comparing COVID situations between BC and Alberta that I hear ALL the time (BC: "Alberta has more cases", Alberta: "It's because we do more testing than you!"). 

Any time I use a ratio to explain something, I also like to see how each contributing variable is impacting the ratio. For example, if the response ratio for Canada is higher, is it because our # of daily new cases went down, or because testing went up?  If a higher percentage of people are testing negative when getting tested, then why are they getting tested in the first place?

I would have liked to see (perhaps as part of the EDA) the distribution of daily tests and new cases on their own before seeing them as a ratio.

**Comment by tanmaysharma19** [comment]
Thank you for taking the time to review and providing your feedback @camharris22. Appreciate it!

**Comment by fatse** [comment]
@camharris22 thank you very much for reviewing our project and providing your constructive feedback.
