### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by MattTPin** [UBC-MDS/covid-19-cases-vs-tests-analysis#74]
Documentation: 

Necessary documentation seems to be all present, well organized, and is professionally and effectively written. 

Code:

No issues running the makefile on my computer and scripts are well organized making the process clear. 

Analysis and Reasoning:

Though process is well explained in final report making it very easy to follow. Conclusions make sense with the information presented. Showing the mathematic equation for Response Ratio makes it easy to clear early on into the analysis.

Communication:

Again, the writing is all well done and pleasant to read. The purpose of the study makes sense and the conclusion that the group has come to is unambiguous. 

Suggestions:

Table 1 only contains a single statistic, likely making the table itself unnecessary as I feel you could likely report just the p-value and it would have the same effect. I'm sure there's a reason for it being like this but as it is it looks a little strange. Additionally, it would be useful to make it more visually clear how the median/average response ratios differ between both countries in the final report (i.e. a mean or median line on the Figure 1 distribution charts) to make the differences more easily understood.

I would personally appreciate if there were also an accompanying file that explains the EDA process since I can see that the group has generated many figures in the results folder that go unused in the final report and an accompanying explanation for many of them would make them easier to process.

**Comment by tanmaysharma19** [comment]
Thank you for taking the time to review and providing your feedback @MattTPin, appreciate it! EDA related workbooks are available under this Milestone https://github.com/UBC-MDS/covid-19-cases-vs-tests-analysis/releases/tag/0.1.0. Thank you!

**Comment by fatse** [comment]
@MattTPin thank you very much for reviewing our project and providing your constructive feedback.
