### ISSUE TITLE
Peer Review from Mitchie Zhao

### ISSUE THREAD

**Issue by shoebillm** [UBC-MDS/covid-19-cases-vs-tests-analysis#75]
Overall, the project is quite interesting and meaningful, and I learned a lot about the current COVID situation in North America by reviewing your project from a statistical perspective. My suggestions are as follows:

**- Documentation:** 
The project repo structure is clear and well-organized. 
The report files are well-written and the rendered format is also good and easy to follow. 

**- Code:**
All codes work well and are readable. 
The makefiles are constructed properly. 

**- Analysis and reasoning:**
Overall, the analysis and reasoning are well-described and the data analysis objective is successfully achieved! 
I really like the "Assumptions and limitations" section where your team clearly states the conditions for your statistically analysis.
For improvement, I think the column name and content of Table 1. could be modified to make it more informative.

**- Communication:** 
The report and proposal are clear and easy to follow in general. However, I do have some suggestions regarding several minor writing style issues: 

1. For formal report writing, it would be better to avoid the use of informal language (e.g. "like"  can be replaced by "such as").

2. I found some citations a bit confusing (may not be consistent): for example, in your report:
<img width="816" alt="Screen Shot 2020-12-10 at 3 02 44 PM" src="https://user-images.githubusercontent.com/48242437/101732817-c36e0580-3af8-11eb-929c-e761998bde34.png">
For the first citation, you wrote "data base created by Hannah Richie et al. (Max Roser and Hasell 2020)", and for in-text citation you used the full name of the person appeared as the 3rd in your bibliography (usually only the first person's last name is needed for in-text citation).  Also, for the citations in your bibliography section, some citations are not in consistent format (e.g. some are with last names followed by a comma while some are with full names followed by a comma; it should be cited as "World Health Organization" instead of "Organization, World Health". 
We also found the same problem while using auto-generated .bib citations, and our solution is to manually revise these citations every time when we import them.

**- Suggestions:** 
The suggestions are provided above specifically under each category.

**Comment by tanmaysharma19** [comment]
Thank you for taking the time to review and providing your feedback @shoebillm. Appreciate it!

**Comment by fatse** [comment]
@shoebillm thank you very much for reviewing our project thoroughly and providing your constructive feedback.

**Comment by nichowu** [comment]
@shoebillm Thanks for your feedback. We have corrected the reference format on Max Roser and Hasell  in PR #77
