### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/covid-19-cases-vs-tests-analysis#80]
Thanks for your submission. I created a virtual environment and installed your dependencies to try to run your make file. I had problmes installing the magick package. I suggest you provide the versions for all your dependencies.

I like that you provide helpful comments throughout the makefile. I suggest you add # usage: as documentation to the main file at the beginning of the file. Also, I suggest you create an env yaml file to make things easier for users to install dependencies.

**Comment by fatse** [comment]
Hey @hsmohammed,

Thank you for your valuable feedback. 

We wrote our Makefile based on  Tiffany's example for [Milestone 3](https://github.com/ttimbers/breast_cancer_predictor/blob/master/Makefile)  as well as the examples in the lecture notes; there was no usage comment about the Makefile inside the Makefile itself. We figured the "Usage" section in the README.md should suffice.
